
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 17 14:22:56 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ELSE = 17;
  public static final int IDENT = 15;
  public static final int PLUS = 11;
  public static final int RBRACE = 4;
  public static final int RPAREN = 7;
  public static final int EQUAL = 12;
  public static final int SEMI = 5;
  public static final int RETURN = 10;
  public static final int IF = 16;
  public static final int LPAREN = 6;
  public static final int LBRACE = 3;
  public static final int COMMA = 8;
  public static final int EOF = 0;
  public static final int NUMBER = 14;
  public static final int PROG = 2;
  public static final int PRINT = 9;
  public static final int error = 1;
  public static final int VOID = 13;
}

